### ISSUE TITLE
请问一下这个怎么使用啊

### ISSUE THREAD

**Issue by zhanghaifei1997** [nianyuguai/longzhuzhu#1]
请问一下这个怎么使用啊

**Comment by nianyuguai** [comment]
> 请问一下这个怎么使用啊

- 1、圈X使用：添加2个Task
```
[task_local]
# crazyJoy金币任务
0/1 * * * * https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/jd_crazy_joy_coin.js, tag=crazyJoy金币任务, img-url=https://raw.githubusercontent.com/58xinian/icon/master/jd_crazy_joy.png, enabled=true
# crazyJoy合成任务
0/10 * * * * https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/jd_crazy_joy_compose.js, tag=crazyJoy合成任务, img-url=https://raw.githubusercontent.com/58xinian/icon/master/jd_crazy_joy.png, enabled=true
```

- 2、云函数
新建一个云函数，专门跑这个，按lxk的云函数方式配置cookie，整个代码上传部署

![image](https://user-images.githubusercontent.com/5230432/109002515-4ad31a00-76e1-11eb-99ff-93e12f68f7e5.png)

**Comment by chihwell** [comment]
> > 请问一下这个怎么使用啊
> 
> * 1、圈X使用：添加2个Task
> 
> ```
> [task_local]
> # crazyJoy金币任务
> 0/1 * * * * https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/jd_crazy_joy_coin.js, tag=crazyJoy金币任务, img-url=https://raw.githubusercontent.com/58xinian/icon/master/jd_crazy_joy.png, enabled=true
> # crazyJoy合成任务
> 0/10 * * * * https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/jd_crazy_joy_compose.js, tag=crazyJoy合成任务, img-url=https://raw.githubusercontent.com/58xinian/icon/master/jd_crazy_joy.png, enabled=true
> ```
> 
> * 2、云函数
>   方法一：新建一个云函数，专门跑这个，按lxk的云函数方式配置cookie，整个代码上传部署运行
>   方法二：和原来的项目一起跑，把两个js拷贝进去，把serverless.yml当中的timer定时器拷贝过去
> 
> ```
>     - timer: # 定时触发器
>         parameters:
>           name: jd_crazy_joy_collect # 触发器名称，默认timer-${name}-${stage}
>           qualifier: $DEFAULT # 别名配置
>           cronExpression: '0/6 * * * * * *'
>           enable: true
>     - timer: # 定时触发器
>         parameters:
>           name: jd_crazy_joy_compose # 触发器名称，默认timer-${name}-${stage}
>           qualifier: $DEFAULT # 别名配置
>           cronExpression: '0 0/15 * * * * *'
>           enable: true
> ```

云函数有900秒超时限制，跑不了吧

**Comment by chihwell** [comment]
如果AC能跑就好

**Comment by nianyuguai** [comment]
> > > 请问一下这个怎么使用啊
> > 
> > 
> > 
> > * 1、圈X使用：添加2个Task
> > 
> > ```
> > [task_local]
> > # crazyJoy金币任务
> > 0/1 * * * * https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/jd_crazy_joy_coin.js, tag=crazyJoy金币任务, img-url=https://raw.githubusercontent.com/58xinian/icon/master/jd_crazy_joy.png, enabled=true
> > # crazyJoy合成任务
> > 0/10 * * * * https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/jd_crazy_joy_compose.js, tag=crazyJoy合成任务, img-url=https://raw.githubusercontent.com/58xinian/icon/master/jd_crazy_joy.png, enabled=true
> > ```
> > 
> > 
> > 
> > * 2、云函数
> >   方法一：新建一个云函数，专门跑这个，按lxk的云函数方式配置cookie，整个代码上传部署运行
> >   方法二：和原来的项目一起跑，把两个js拷贝进去，把serverless.yml当中的timer定时器拷贝过去
> > 
> > ```
> >     - timer: # 定时触发器
> >         parameters:
> >           name: jd_crazy_joy_collect # 触发器名称，默认timer-${name}-${stage}
> >           qualifier: $DEFAULT # 别名配置
> >           cronExpression: '0/6 * * * * * *'
> >           enable: true
> >     - timer: # 定时触发器
> >         parameters:
> >           name: jd_crazy_joy_compose # 触发器名称，默认timer-${name}-${stage}
> >           qualifier: $DEFAULT # 别名配置
> >           cronExpression: '0 0/15 * * * * *'
> >           enable: true
> > ```
> 
> 云函数有900秒超时限制，跑不了吧

就是解决云函数超时问题，6秒一次
