### ISSUE TITLE
已赞赏。一些想法和建议给男神

### ISSUE THREAD

**Issue by N1rEn** [nianyuguai/longzhuzhu#17]
大清早看到圈X群的讨论，很替鲶鱼抱不平，免费的东西被拿去盈利的确是令人愤怒的事。

已经赞赏了男神并留了微信，不知道男神能不能看到。

个人觉得因为一些蛀虫而放弃这么被大家喜欢的脚本有点可惜，能不能建立一个实名验证的付费小群或者一对一付费验证之类的方法让铁粉能继续使用，最大化的避免二道贩子。

反正我是希望可以继续用到您的插件的，付费也没有问题。

祝男神天天开心！头发越来越多！

**Comment by WinterBoring** [comment]
顶一个！
