### ISSUE TITLE
麻烦问一下 为什么有的账号是未登录状态

### ISSUE THREAD

**Issue by 97Czl** [nianyuguai/longzhuzhu#18]
有部分账号显示未登录，但是使用的lxk的其他脚本是可以用的。只有红包雨会出现未登陆的信息提示，无法正常执行
![image](https://user-images.githubusercontent.com/48757692/117752112-ce17fc80-b248-11eb-8367-b0d2a162099d.png)

**Comment by nianyuguai** [comment]
> 有部分账号显示未登录，但是使用的lxk的其他脚本是可以用的。只有红包雨会出现未登陆的信息提示，无法正常执行
> ![image](https://user-images.githubusercontent.com/48757692/117752112-ce17fc80-b248-11eb-8367-b0d2a162099d.png)

第一次说有反馈这个情况，重新录ck看看

**Comment by 97Czl** [comment]
> > 有部分账号显示未登录，但是使用的lxk的其他脚本是可以用的。只有红包雨会出现未登陆的信息提示，无法正常执行
> > ![image](https://user-images.githubusercontent.com/48757692/117752112-ce17fc80-b248-11eb-8367-b0d2a162099d.png)
> 
> 第一次说有反馈这个情况，重新录ck看看

好的 我试试 多谢多谢
