### ISSUE TITLE
召唤龙王失败，召唤神龙成功，但是它怎么出差了？

### ISSUE THREAD

**Issue by notget** [nianyuguai/longzhuzhu#19]
==================脚本执行- 北京时间(UTC+8)：2021/5/12上午12:01:01=====================

召唤龙王: https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/qx/jd-live-rain.json
"connect ECONNREFUSED 0.0.0.0:443"
召唤龙王失败, 召唤神龙: http://jd-1255594201.file.myqcloud.com/jd-live-rain.json
召唤完成
今日龙王🐲出差，天气晴朗☀️，改日再来～

🔔整点京豆雨, 结束! 🕛 3.826 秒

**Comment by nianyuguai** [comment]
> ==================脚本执行- 北京时间(UTC+8)：2021/5/12上午12:01:01=====================
> 
> 召唤龙王: https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/qx/jd-live-rain.json
> "connect ECONNREFUSED 0.0.0.0:443"
> 召唤龙王失败, 召唤神龙: http://jd-1255594201.file.myqcloud.com/jd-live-rain.json
> 召唤完成
> 今日龙王🐲出差，天气晴朗☀️，改日再来～
> 
> 🔔整点京豆雨, 结束! 🕛 3.826 秒

配置有缓存，凌晨在59分才会更新RRA，所以凌晨其他时间点多跑一次，自己多加一个cron
5 0 * * *
