### ISSUE TITLE
求大佬告知这是怎么回事，昨天还可以就今天不行了

### ISSUE THREAD

**Issue by kaikii98** [nianyuguai/longzhuzhu#21]
召唤龙王: https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/qx/jd-live-rain.json
"connect ECONNREFUSED 151.101.228.133:443"
召唤龙王失败, 召唤神龙: http://jd-1255594201.file.myqcloud.com/jd-live-rain.json
"Response code 404 (Not Found)"
召唤完成
今日龙王🐲出差，天气晴朗☀️，改日再来～

**Comment by nianyuguai** [comment]
> 召唤龙王: https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/qx/jd-live-rain.json
> "connect ECONNREFUSED 151.101.228.133:443"
> 召唤龙王失败, 召唤神龙: http://jd-1255594201.file.myqcloud.com/jd-live-rain.json
> "Response code 404 (Not Found)"
> 召唤完成
> 今日龙王🐲出差，天气晴朗☀️，改日再来～

https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/qx/jd-live-rain.json
这个文件已经删除了，你这脚本过期了，更新脚本

**Comment by kaikii98** [comment]
召唤龙王~
召唤完成
龙王就位: RRA3gsDuBBP5kYqknjTZ2h3VLkEpiT3

RRA: RRA3gsDuBBP5kYqknjTZ2h3VLkEpiT3


******开始【京东账号1】jd_6f87e12022e89*********

今日次数已满

> > 召唤龙王: https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/qx/jd-live-rain.json
> > "connect ECONNREFUSED 151.101.228.133:443"
> > 召唤龙王失败, 召唤神龙: http://jd-1255594201.file.myqcloud.com/jd-live-rain.json
> > "Response code 404 (Not Found)"
> > 召唤完成
> > 今日龙王🐲出差，天气晴朗☀️，改日再来～
> 
> https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/qx/jd-live-rain.json
> 这个文件已经删除了，你这脚本过期了，更新脚本

能跑了但是出现了这个，今天是不是不能获得了
召唤龙王~
召唤完成
龙王就位: RRA3gsDuBBP5kYqknjTZ2h3VLkEpiT3

RRA: RRA3gsDuBBP5kYqknjTZ2h3VLkEpiT3


******开始【京东账号1】jd_6f87e12022e89*********

今日次数已满
