### ISSUE TITLE
大佬借用了你的脚本如果有不合适或是不让用的我提前删除，也是群友提供的，如果不让用的话麻烦留言给我我删代码

### ISSUE THREAD

**Issue by 1314mjf521** [nianyuguai/longzhuzhu#6]
项目地址：如果要协同开发的话请留言
https://gitee.com/mjf521/JD-FreeFuck

**Comment by nianyuguai** [comment]
> 项目地址：如果要协同开发的话请留言
> https://gitee.com/mjf521/JD-FreeFuck

不建议集成，请删除，有需要的道友自己引

**Comment by 1314mjf521** [comment]
好的
