### ISSUE TITLE
获取龙王信号: https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/qx/jd-live-rain.json "connect ECONNREFUSED 0.0.0.0:443"这个啥意思？

### ISSUE THREAD

**Issue by hecarli555** [nianyuguai/longzhuzhu#7]
提示这个“获取龙王信号: https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/qx/jd-live-rain.json
"connect ECONNREFUSED 0.0.0.0:443"”是啥意思？如何解决呢？

**Comment by nianyuguai** [comment]
> 提示这个“获取龙王信号: https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/qx/jd-live-rain.json
> "connect ECONNREFUSED 0.0.0.0:443"”是啥意思？如何解决呢？

网络问题、dns污染、并发访问人过多，都有可能导致，docker可以用腾讯云的cdn链接规避
`export JD_RRA_URL="http://jd-1255594201.file.myqcloud.com/jd-live-rain.json" `

**Comment by nianyuguai** [comment]
> 提示这个“获取龙王信号: https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/qx/jd-live-rain.json
> "connect ECONNREFUSED 0.0.0.0:443"”是啥意思？如何解决呢？

优化了一下，如果raw失败重试cdn链接

**Comment by hecarli555** [comment]
> > 提示这个“获取龙王信号: https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/qx/jd-live-rain.json
> > "connect ECONNREFUSED 0.0.0.0:443"”是啥意思？如何解决呢？
> 
> 优化了一下，如果raw失败重试cdn链接

昨晚开始龙王又不灵光了…这次要怎么修改？

**Comment by nianyuguai** [comment]
> > > 提示这个“获取龙王信号: https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/qx/jd-live-rain.json
> > > "connect ECONNREFUSED 0.0.0.0:443"”是啥意思？如何解决呢？
> > 
> > 
> > 优化了一下，如果raw失败重试cdn链接
> 
> 昨晚开始龙王又不灵光了…这次要怎么修改？

应该解决了，有问题可以发出来

**Comment by hecarli555** [comment]
> > > > 提示这个“获取龙王信号: https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/qx/jd-live-rain.json
> > > > "connect ECONNREFUSED 0.0.0.0:443"”是啥意思？如何解决呢？
> > > 
> > > 
> > > 优化了一下，如果raw失败重试cdn链接
> > 
> > 
> > 昨晚开始龙王又不灵光了…这次要怎么修改？
> 
> 应该解决了，有问题可以发出来

跑了下，提示活动火爆意思是被黑了么…
